module dram_PHY (
    input  wire         APBCLK,
    input  wire         DfiClk,
    input  wire         DfiCtlClk,
    input  wire         BypassPclk,
    input  wire         PRESETn_APB,

    input  wire         Reset, // warm reset
    input  wire         PwrOk,
    input  wire [31:0]  PADDR_APB,
    input  wire         PWRITE_APB,
    input  wire         PSELx_APB,
    input  wire         PENABLE_APB,
    input  wire [15:0]  PWDATA_APB,
    input  wire [1:0]   PSTRB_APB,
    input  wire [2:0]   PPROT_APB,
    output wire         PREADY_APB,
    output wire [15:0]  PRDATA_APB,
    output wire         PSLVERR_APB,
    input  wire [2:0]   PPROT_PIN,

    // DFI Interface
    input  wire         dfi_reset_n,
    output wire         dfi0_ctrlupd_ack,
    input  wire         dfi0_ctrlupd_req,
    input  wire         dfi0_phyupd_ack,
    output wire         dfi0_phyupd_req,
    output wire [1:0]   dfi0_phyupd_type,
    input  wire         dfi0_dram_clk_disable,
    input  wire [4:0]   dfi0_freq,
    input  wire [1:0]   dfi0_freq_ratio,
    output wire         dfi0_init_complete,
    input  wire         dfi0_init_start,
    input  wire         dfi0_phymstr_ack,
    output wire [1:0]   dfi0_phymstr_cs_state,
    output wire         dfi0_phymstr_req,
    output wire         dfi0_phymstr_state_sel,
    output wire [1:0]   dfi0_phymstr_type,
    input  wire [5:0]   dfi0_address_P0,
    input  wire [5:0]   dfi0_address_P1,
    input  wire [5:0]   dfi0_address_P2,
    input  wire [5:0]   dfi0_address_P3,
    input  wire [1:0]   dfi0_cke_P0,
    input  wire [1:0]   dfi0_cke_P1,
    input  wire [1:0]   dfi0_cke_P2,
    input  wire [1:0]   dfi0_cke_P3,
    input  wire [1:0]   dfi0_cs_P0,
    input  wire [1:0]   dfi0_cs_P1,
    input  wire [1:0]   dfi0_cs_P2,
    input  wire [1:0]   dfi0_cs_P3,
    output wire         dfi0_lp_ack,
    input  wire         dfi0_lp_ctrl_req,
    input  wire         dfi0_lp_data_req,
    input  wire  [3:0]  dfi0_lp_wakeup,
    output wire         dfi0_error,
    output wire [3:0]   dfi0_error_info,
    input  wire [31:0]  dfi_wrdata_P0,
    input  wire [31:0]  dfi_wrdata_P1,
    input  wire [31:0]  dfi_wrdata_P2,
    input  wire [31:0]  dfi_wrdata_P3,
    input  wire [3:0]   dfi_wrdata_cs_n_P0,
    input  wire [3:0]   dfi_wrdata_cs_n_P1,
    input  wire [3:0]   dfi_wrdata_cs_n_P2,
    input  wire [3:0]   dfi_wrdata_cs_n_P3,
    input  wire [1:0]   dfi_wrdata_en_P0,
    input  wire [1:0]   dfi_wrdata_en_P1,
    input  wire [1:0]   dfi_wrdata_en_P2,
    input  wire [1:0]   dfi_wrdata_en_P3,
    input  wire [3:0]   dfi_wrdata_mask_P0,
    input  wire [3:0]   dfi_wrdata_mask_P1,
    input  wire [3:0]   dfi_wrdata_mask_P2,
    input  wire [3:0]   dfi_wrdata_mask_P3,
    output wire [31:0]  dfi_rddata_W0,
    output wire [31:0]  dfi_rddata_W1,
    output wire [31:0]  dfi_rddata_W2,
    output wire [31:0]  dfi_rddata_W3,
    input  wire [3:0]   dfi_rddata_cs_n_P0,
    input  wire [3:0]   dfi_rddata_cs_n_P1,
    input  wire [3:0]   dfi_rddata_cs_n_P2,
    input  wire [3:0]   dfi_rddata_cs_n_P3,
    output wire [3:0]   dfi_rddata_dbi_W0,
    output wire [3:0]   dfi_rddata_dbi_W1,
    output wire [3:0]   dfi_rddata_dbi_W2,
    output wire [3:0]   dfi_rddata_dbi_W3,
    input  wire [1:0]   dfi_rddata_en_P0,
    input  wire [1:0]   dfi_rddata_en_P1,
    input  wire [1:0]   dfi_rddata_en_P2,
    input  wire [1:0]   dfi_rddata_en_P3,
    output wire [1:0]   dfi_rddata_valid_W0,
    output wire [1:0]   dfi_rddata_valid_W1,
    output wire [1:0]   dfi_rddata_valid_W2,
    output wire [1:0]   dfi_rddata_valid_W3,


    input  wire         WSI,                  
    input  wire         TDRCLK,                 
    input  wire         WRSTN,                
    input  wire         DdrPhyCsrCmdTdrShiftEn,    
    input  wire         DdrPhyCsrCmdTdrCaptureEn,  
    input  wire         DdrPhyCsrCmdTdrUpdateEn,   
    output wire         DdrPhyCsrCmdTdr_Tdo,       
    input  wire         DdrPhyCsrRdDataTdrShiftEn,    
    input  wire         DdrPhyCsrRdDataTdrCaptureEn,  
    input  wire         DdrPhyCsrRdDataTdrUpdateEn,   
    output wire         DdrPhyCsrRdDataTdr_Tdo,       

    output wire         dwc_ddrphy_int_n, 
   
    output wire         dwc_ddrphy_dto,   


    input  wire [5:0]   atpg_se,
    input  wire [85:0]  atpg_si,
    output wire [85:0]  atpg_so,
    input  wire         atpg_mode,
    input  wire [5:0]   atpg_lu_ctrl,

    input  wire         atpg_RDQSClk,
    input  wire         atpg_Pclk,
    input  wire         atpg_TxDllClk,

    input  wire [31:0]  iccm_data_dout,
    output wire [31:0]  iccm_data_din,
    output wire [14:2]  iccm_data_addr,
    output wire         iccm_data_ce,
    output wire         iccm_data_we,
    output wire [ 3:0]  iccm_data_wem,

    input  wire [31:0]  dccm_data_dout,
    output wire [31:0]  dccm_data_din,
    output wire [14:2]  dccm_data_addr,
    output wire         dccm_data_ce,
    output wire         dccm_data_we,
    output wire [3:0]   dccm_data_wem,

    output wire         pmu_sram_clk_gated,


    input  wire         BypassModeEnAC,
    input  wire [11:0]  BypassOutEnAC,
    input  wire [11:0]  BypassOutDataAC,
    output wire [11:0]  BypassInDataAC,

    input  wire         BypassModeEnDAT,
    input  wire [23:0]  BypassOutEnDAT,
    input  wire [23:0]  BypassOutDataDAT,
    output wire [23:0]  BypassInDataDAT,

    input  wire         BypassModeEnMASTER,
    input  wire [1:0]   BypassOutEnMASTER,
    input  wire [1:0]   BypassOutDataMASTER,
    output wire [1:0]   BypassInDataMASTER,

    output wire         DDR4_CK_T,
    output wire         DDR4_CK_C,
    output wire [1:0]   DDR4_CKE,
    output wire [1:0]   DDR4_CS_N,
    output wire [5:0]   DDR4_ADR,
    output wire         DDR4_ODT,
    inout  wire [1:0]   DDR4_DQS_T,
    inout  wire [1:0]   DDR4_DQS_C,
    inout  wire [15:0]  DDR4_DQ,
    inout  wire [1:0]   DDR4_DM_DBI_N,

    output wire         BP_MEMRESET_L,
    inout wire          BP_ALERT_N,
    inout wire          BP_VREF,

    input  wire         BP_ZN_SENSE,
    output wire         BP_ZN

);

`include "dwc_ddrphy_VDEFINES.v"

wire [23:0] BP_D;
wire [11:0] BP_A;

assign DDR4_CKE[1:0] = BP_A[1:0];
assign DDR4_CS_N[1:0] = BP_A[7:6];
assign DDR4_ADR = {BP_A[11:8],BP_A[3:2]};
assign DDR4_CK_T = BP_A[4];
assign DDR4_CK_C = BP_A[5];

generate
    for(genvar i=0; i< 2; i=i+1) begin: g_BP_D
        tran dm_xmit (DDR4_DM_DBI_N[i] , BP_D[12*i+8]);
        tran dqs_u0_t_xmit (DDR4_DQS_T[i] , BP_D[12*i+9]);
        tran dqs_u0_c_xmit (DDR4_DQS_C[i] , BP_D[12*i+10]);
    end
endgenerate
generate
    for(genvar i=0; i< 2; i=i+1) begin: g_BP_DQ
    for (genvar j=0; j<8; j=j+1)begin: g_BP_DQ2
        tran dqs_dq_xmit   (DDR4_DQ[8*i+j] , BP_D[12*i+j]);
    end
    end
endgenerate

dwc_ddrphy_top u_ddrphy_top(
    // APB Interface
    .APBCLK(APBCLK),
    .DfiClk(DfiClk),
    .DfiCtlClk(DfiCtlClk),
    .BypassPclk(BypassPclk),

    .PRESETn_APB(PRESETn_APB),

    .Reset(Reset),
    .PwrOkIn(PwrOk),

    .PSELx_APB(PSELx_APB),
    .PENABLE_APB(PENABLE_APB),
    .PWDATA_APB(PWDATA_APB),
    .PSTRB_APB(PSTRB_APB),
    .PADDR_APB({10'h000,PADDR_APB[23:2]}),
    .PWRITE_APB(PWRITE_APB),
    .PPROT_APB(PPROT_APB),
    .PRDATA_APB(PRDATA_APB),
    .PSLVERR_APB(PSLVERR_APB),
    .PREADY_APB(PREADY_APB),
    .PPROT_PIN(PPROT_PIN),

    // DFI Interface
    .dfi_reset_n(dfi_reset_n),
    .dfi0_ctrlupd_ack(dfi0_ctrlupd_ack),
    .dfi0_ctrlupd_req(dfi0_ctrlupd_req),
    .dfi0_phyupd_ack(dfi0_phyupd_ack),
    .dfi0_phyupd_req(dfi0_phyupd_req),
    .dfi0_phyupd_type(dfi0_phyupd_type),
    .dfi0_dram_clk_disable(dfi0_dram_clk_disable),
    .dfi0_freq(dfi0_freq),
    .dfi0_freq_ratio(dfi0_freq_ratio),
    .dfi0_init_complete(dfi0_init_complete),
    .dfi0_init_start(dfi0_init_start),
    .dfi0_phymstr_ack(dfi0_phymstr_ack),
    .dfi0_phymstr_cs_state(dfi0_phymstr_cs_state),
    .dfi0_phymstr_req(dfi0_phymstr_req),
    .dfi0_phymstr_state_sel(dfi0_phymstr_state_sel),
    .dfi0_phymstr_type(dfi0_phymstr_type),
    .dfi0_address_P0(dfi0_address_P0),
    .dfi0_address_P1(dfi0_address_P1),
    .dfi0_address_P2(dfi0_address_P2),
    .dfi0_address_P3(dfi0_address_P3),
    .dfi0_cke_P0(dfi0_cke_P0),
    .dfi0_cke_P1(dfi0_cke_P1),
    .dfi0_cke_P2(dfi0_cke_P2),
    .dfi0_cke_P3(dfi0_cke_P3),
    .dfi0_cs_P0(dfi0_cs_P0),
    .dfi0_cs_P1(dfi0_cs_P1),
    .dfi0_cs_P2(dfi0_cs_P2),
    .dfi0_cs_P3(dfi0_cs_P3),
    .dfi0_lp_ack(dfi0_lp_ack),
    .dfi0_lp_ctrl_req(dfi0_lp_ctrl_req),
    .dfi0_lp_data_req(dfi0_lp_data_req),
    .dfi0_lp_wakeup(dfi0_lp_wakeup),
    .dfi0_error(dfi0_error),
    .dfi0_error_info(dfi0_error_info),
    .dfi_wrdata_P0(dfi_wrdata_P0),
    .dfi_wrdata_P1(dfi_wrdata_P1),
    .dfi_wrdata_P2(dfi_wrdata_P2),
    .dfi_wrdata_P3(dfi_wrdata_P3),
    .dfi_wrdata_cs_n_P0(dfi_wrdata_cs_n_P0),
    .dfi_wrdata_cs_n_P1(dfi_wrdata_cs_n_P1),
    .dfi_wrdata_cs_n_P2(dfi_wrdata_cs_n_P2),
    .dfi_wrdata_cs_n_P3(dfi_wrdata_cs_n_P3),
    .dfi_wrdata_en_P0(dfi_wrdata_en_P0),
    .dfi_wrdata_en_P1(dfi_wrdata_en_P1),
    .dfi_wrdata_en_P2(dfi_wrdata_en_P2),
    .dfi_wrdata_en_P3(dfi_wrdata_en_P3),
    .dfi_wrdata_mask_P0(dfi_wrdata_mask_P0),
    .dfi_wrdata_mask_P1(dfi_wrdata_mask_P1),
    .dfi_wrdata_mask_P2(dfi_wrdata_mask_P2),
    .dfi_wrdata_mask_P3(dfi_wrdata_mask_P3),
    .dfi_rddata_W0(dfi_rddata_W0),
    .dfi_rddata_W1(dfi_rddata_W1),
    .dfi_rddata_W2(dfi_rddata_W2),
    .dfi_rddata_W3(dfi_rddata_W3),
    .dfi_rddata_cs_n_P0(dfi_rddata_cs_n_P0),
    .dfi_rddata_cs_n_P1(dfi_rddata_cs_n_P1),
    .dfi_rddata_cs_n_P2(dfi_rddata_cs_n_P2),
    .dfi_rddata_cs_n_P3(dfi_rddata_cs_n_P3),
    .dfi_rddata_dbi_W0(dfi_rddata_dbi_W0),
    .dfi_rddata_dbi_W1(dfi_rddata_dbi_W1),
    .dfi_rddata_dbi_W2(dfi_rddata_dbi_W2),
    .dfi_rddata_dbi_W3(dfi_rddata_dbi_W3),
    .dfi_rddata_en_P0(dfi_rddata_en_P0),
    .dfi_rddata_en_P1(dfi_rddata_en_P1),
    .dfi_rddata_en_P2(dfi_rddata_en_P2),
    .dfi_rddata_en_P3(dfi_rddata_en_P3),
    .dfi_rddata_valid_W0(dfi_rddata_valid_W0),
    .dfi_rddata_valid_W1(dfi_rddata_valid_W1),
    .dfi_rddata_valid_W2(dfi_rddata_valid_W2),
    .dfi_rddata_valid_W3(dfi_rddata_valid_W3),
    .WSI(WSI),
    .TDRCLK(TDRCLK),
    .WRSTN(WRSTN),
    .DdrPhyCsrCmdTdrShiftEn(DdrPhyCsrCmdTdrShiftEn),
    .DdrPhyCsrCmdTdrCaptureEn(DdrPhyCsrCmdTdrCaptureEn),
    .DdrPhyCsrCmdTdrUpdateEn(DdrPhyCsrCmdTdrUpdateEn),
    .DdrPhyCsrCmdTdr_Tdo(DdrPhyCsrCmdTdr_Tdo),
    .DdrPhyCsrRdDataTdrShiftEn(DdrPhyCsrRdDataTdrShiftEn),
    .DdrPhyCsrRdDataTdrCaptureEn(DdrPhyCsrRdDataTdrCaptureEn),
    .DdrPhyCsrRdDataTdrUpdateEn(DdrPhyCsrRdDataTdrUpdateEn),
    .DdrPhyCsrRdDataTdr_Tdo(DdrPhyCsrRdDataTdr_Tdo),
    .dwc_ddrphy_int_n(dwc_ddrphy_int_n),
    .dwc_ddrphy_dto(dwc_ddrphy_dto),
    .atpg_se(atpg_se),
    .atpg_si(atpg_si),
    .atpg_so(atpg_so),
    .atpg_mode(atpg_mode),
    .atpg_lu_ctrl(atpg_lu_ctrl),
    .atpg_RDQSClk(atpg_RDQSClk),
    .atpg_Pclk(atpg_Pclk),
    .atpg_TxDllClk(atpg_TxDllClk),
    .iccm_data_dout(iccm_data_dout),
    .iccm_data_din(iccm_data_din),
    .iccm_data_addr(iccm_data_addr),
    .iccm_data_ce(iccm_data_ce),
    .iccm_data_we(iccm_data_we),
    .iccm_data_wem(iccm_data_wem),
    .dccm_data_dout(dccm_data_dout),
    .dccm_data_din(dccm_data_din),
    .dccm_data_addr(dccm_data_addr),
    .dccm_data_ce(dccm_data_ce),
    .dccm_data_we(dccm_data_we),
    .dccm_data_wem(dccm_data_wem),
    .pmu_sram_clk_gated(pmu_sram_clk_gated),
    .BypassModeEnAC(BypassModeEnAC),
    .BypassOutEnAC(BypassOutEnAC),
    .BypassOutDataAC(BypassOutDataAC),
    .BypassInDataAC(BypassInDataAC),
    .BypassModeEnDAT(BypassModeEnDAT),
    .BypassOutEnDAT(BypassOutEnDAT),
    .BypassOutDataDAT(BypassOutDataDAT),
    .BypassInDataDAT(BypassInDataDAT),
    .BypassModeEnMASTER(BypassModeEnMASTER),
    .BypassOutEnMASTER(BypassOutEnMASTER),
    .BypassOutDataMASTER(BypassOutDataMASTER),
    .BypassInDataMASTER(BypassInDataMASTER),
    .BP_D(BP_D),
    .BP_A(BP_A),
    .BP_MEMRESET_L(BP_MEMRESET_L),
    .BP_ALERT_N(BP_ALERT_N),
    .BP_VREF(BP_VREF),
    .BP_ZN_SENSE(BP_ZN_SENSE),
    .BP_ZN(BP_ZN)

);

endmodule
